__all__ = ["WRITE_TOOLS", "ALL_TOOLS", "register_all"]

from zbbx_mcp.resolver import InstanceResolver
from zbbx_mcp.tools import (
    alerts,
    analysis,
    audit,
    availability,
    ceo_report,
    configuration,
    correlation,
    costs,
    dashboard_report,
    dashboards,
    discovery,
    disruption,
    domains,
    events,
    executive,
    floods,
    full_report,
    geo_health,
    geo_traffic,
    health,
    hostgroups,
    hosts,
    html_report,
    infra_report,
    inventory_load,
    inventory_map,
    ip_history,
    items,
    loss_drift,
    macros,
    maintenance,
    maps,
    media,
    problems,
    proxies,
    report,
    risk,
    rollback_tools,
    scripts,
    service_brief,
    services,
    slack,
    templates,
    traffic,
    trends_compare,
    trends_health,
    triggers,
    users,
    web_scenarios,
)

# Tools that modify data — blocked in read-only mode
WRITE_TOOLS = frozenset({
    "acknowledge_problem",
    "bulk_acknowledge",
    # Host CRUD
    "create_host",
    "update_host",
    "delete_host",
    # Host group CRUD
    "create_hostgroup",
    "delete_hostgroup",
    # Item CRUD
    "create_item",
    "update_item",
    "delete_item",
    # Trigger CRUD
    "create_trigger",
    "update_trigger",
    "delete_trigger",
    # Template linking
    "link_template",
    "unlink_template",
    # Maintenance
    "create_maintenance",
    "delete_maintenance",
    # Configuration
    "import_configuration",
    # Scripts
    "execute_script",
    # Macros
    "set_host_macro",
    "set_bulk_macro",
    "delete_host_macro",
    # Rollback
    "rollback_last",
    "rollback_by_index",
    # Costs
    "import_server_costs",
    "import_costs_by_ip",
    "set_bulk_cost",
    "fill_cost_median",
    "import_from_xlsx",
})


# Canonical name list for every tool the server registers when nothing is
# disabled. ZABBIX_TIER restriction subtracts from this; tests assert that
# FastMCP registers exactly this set. Keep alphabetised.
ALL_TOOLS: frozenset[str] = frozenset({
    "acknowledge_problem",
    "analyze_cost_import",
    "analyze_server_roles",
    "audit_external_ips",
    "audit_host_ips",
    "bulk_acknowledge",
    "check_connection",
    "classify_external_ips",
    "compare_servers",
    "correlate_logs",
    "create_host",
    "create_hostgroup",
    "create_item",
    "create_maintenance",
    "create_trigger",
    "delete_host",
    "delete_host_macro",
    "delete_hostgroup",
    "delete_item",
    "delete_maintenance",
    "delete_trigger",
    "detect_cost_anomalies",
    "detect_disruption_wave",
    "detect_loss_drift",
    "detect_regional_anomalies",
    "detect_regional_traffic_loss",
    "detect_service_port_split",
    "detect_traffic_anomalies",
    "detect_traffic_drops",
    "execute_script",
    "export_configuration",
    "export_cost_audit",
    "export_dashboard",
    "fill_cost_median",
    "find_host_dashboard",
    "find_stale_billing_ips",
    "generate_ceo_report",
    "generate_full_report",
    "generate_html_report",
    "generate_infra_report",
    "generate_product_map",
    "generate_server_report",
    "generate_service_brief",
    "get_actions",
    "get_active_problems",
    "get_agent_unreachable",
    "get_alert_summary",
    "get_alerts",
    "get_at_risk_hosts",
    "get_audit_log",
    "get_capacity_planning",
    "get_correlated_events",
    "get_cost_efficiency",
    "get_cost_gaps",
    "get_cost_summary",
    "get_dashboard_detail",
    "get_dashboards",
    "get_discovery_rules",
    "get_disruption_blast_radius",
    "get_domain_list",
    "get_domain_status",
    "get_error_rate",
    "get_event_frequency",
    "get_events",
    "get_executive_dashboard",
    "get_expansion_report",
    "get_external_ip_history",
    "get_fleet_risk_score",
    "get_geo_traffic_trends",
    "get_global_macros",
    "get_graphs",
    "get_health_assessment",
    "get_high_cpu_servers",
    "get_host",
    "get_host_availability",
    "get_host_floods",
    "get_host_items",
    "get_host_macros",
    "get_hostgroups",
    "get_idle_relays",
    "get_incident_report",
    "get_item_history",
    "get_latency_estimate",
    "get_low_disk_servers",
    "get_low_memory_servers",
    "get_maintenance",
    "get_map_detail",
    "get_maps",
    "get_media_types",
    "get_month_over_month",
    "get_outage_clusters",
    "get_peak_analysis",
    "get_predictive_alerts",
    "get_problem_age_buckets",
    "get_problem_detail",
    "get_problems",
    "get_product_audit",
    "get_product_summary",
    "get_provider_summary",
    "get_proxies",
    "get_recent_changes",
    "get_recovery_score",
    "get_regional_density_map",
    "get_report_snapshot",
    "get_rollback_history",
    "get_scripts",
    "get_server_clusters",
    "get_server_dashboard",
    "get_server_load",
    "get_server_map",
    "get_servers_by_ping",
    "get_service_health_matrix",
    "get_service_uptime_report",
    "get_services",
    "get_shutdown_candidates",
    "get_sla",
    "get_sla_dashboard",
    "get_ssl_expiry",
    "get_stale_items",
    "get_stale_servers",
    "get_templates",
    "get_traffic_drop_timeline",
    "get_traffic_report",
    "get_trends",
    "get_trends_batch",
    "get_trigger_timeline",
    "get_triggers",
    "get_underloaded_servers",
    "get_unknown_providers",
    "get_users",
    "get_web_scenario_status",
    "get_web_scenarios",
    "identify_providers",
    "import_cluster_ip_fees",
    "import_configuration",
    "import_costs_by_ip",
    "import_from_xlsx",
    "import_server_costs",
    "link_template",
    "reconcile_billing_audit",
    "rollback_by_index",
    "rollback_last",
    "search_hosts",
    "search_hosts_by_ip",
    "search_hosts_by_location",
    "search_items",
    "send_slack_message",
    "send_slack_report",
    "set_bulk_cost",
    "set_bulk_macro",
    "set_host_macro",
    "unlink_template",
    "update_host",
    "update_item",
    "update_trigger",
})


def register_all(
    mcp,
    resolver: InstanceResolver,
    read_only: bool = False,
    disabled_tools: frozenset[str] = frozenset(),
):
    skip: set[str] = set()

    if read_only:
        skip.update(WRITE_TOOLS)

    if disabled_tools:
        skip.update(disabled_tools)

    modules = [
        hosts, problems, hostgroups, health, dashboards, items, availability, audit,
        triggers, templates, maintenance, events, discovery,
        configuration, scripts, services, macros, rollback_tools,
        inventory_map, inventory_load, report, alerts, users, proxies, maps, media, slack, domains,
        infra_report, costs, traffic, dashboard_report, full_report,
        trends_compare, trends_health,
        html_report, geo_traffic, geo_health, executive, ceo_report, service_brief, analysis,
        web_scenarios, correlation, ip_history, loss_drift, disruption, risk, floods,
    ]
    for module in modules:
        module.register(mcp, resolver, skip=skip)
